name: "GitHub App Auth"
description: "Authenticate as a GitHub App"
inputs:
  app-id:
    description: App ID of the GitHub app
    required: true
  private-key:
    description: Private key of the GitHub app
    required: true
  installation-id:
    description: Installation ID of the GitHub app in an organization or account. Only required if multiple installations exist.
    required: false
  set-git-credentials:
    description: Configures git credentials for GitHub URLs if set to "true"
    required: false
    default: 'false'
    options:
      - true
      - false
outputs:
  access-token:
    description: Access Token for the GitHub App installation
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: 'download-cloud'
  color: 'blue'